import './globals.css';
import Indexes from '@/components/Indexes';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'ekşi sözlük - kutsal bilgi kaynağı',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-sourBG text-sourText">
        <div className="w-screen h-1 bg-sour fixed"></div>
        <div className="container">
          <Header />
          <main className="main flex min-h-screen flex-col">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
